### ISSUE TITLE
python 3.12 编译报错

### ISSUE THREAD

**Issue by skyoffcx** [x-eks-fusion/xfusion#41]
(v1.2.0) PS D:\xfusion\hello> xf build   
23:46:38: run build
23:46:38: scan config
23:46:38: scan config done
23:46:38: run script D:\xfusion\components\xf_hal\xf_collect.py
23:46:38: run script D:\xfusion\components\xf_heap\xf_collect.py
23:46:38: run script D:\xfusion\components\xf_init\xf_collect.py
23:46:38: run script D:\xfusion\components\xf_log\xf_collect.py
23:46:38: run script D:\xfusion\components\xf_nal\xf_collect.py
23:46:38: run script D:\xfusion\components\xf_net_apps\xf_collect.py
23:46:38: run script D:\xfusion\components\xf_osal\xf_collect.py
23:46:38: run script D:\xfusion\components\xf_sys\xf_collect.py
23:46:38: run script D:\xfusion\components\xf_task\xf_collect.py
23:46:38: run script D:\xfusion\components\xf_utils\xf_collect.py
23:46:38: run script D:\xfusion\components\xf_wal\xf_collect.py
23:46:38: run script D:\xfusion\hello\main\xf_collect.py
23:46:38: Template applied successfully to D:\xfusion\hello\build\build_environ.cmake
23:46:38: exec cmd python build.py -c -nhso -release bs21e-sle-ble-slp-central-peripheral
D:\xfusion\sdks\bs2x_sdk\build\script\sdk_generator\target_config_genarator.py:13: SyntaxWarning: invalid escape sequence '\s'
r = re.search("['\"]%s['\"](\s*):[\d\D\r\n]*?\}(\s*)," % config, lines)
D:\xfusion\sdks\bs2x_sdk\build\script\sdk_generator\target_config_genarator.py:16: SyntaxWarning: invalid escape sequence '\{'
lines = re.sub("(target|target_template) = \{\n([\w\W]*?\n)\}",
D:\xfusion\sdks\bs2x_sdk\build\script\sdk_generator\target_config_genarator.py:18: SyntaxWarning: invalid escape sequence '\{'
lines = re.sub("target_copy = \{\n([\w\W]*?\n)\}",
D:\xfusion\sdks\bs2x_sdk\build\script\sdk_generator\target_config_genarator.py:20: SyntaxWarning: invalid escape sequence '\{'
lines = re.sub("target_group = \{\n([\w\W]*?\n)\}",
warning: default on the choice symbol SUPPORT_SLE_PERIPHERAL (defined at application/samples/products/sle_mouse_with_dongle/Kconfig:56, protocol/Kconfig:8) will have no effect, as defaults do not affect choice symbols
warning: the choice symbol SUPPORT_SLE_PERIPHERAL (defined at application/samples/products/sle_mouse_with_dongle/Kconfig:56, protocol/Kconfig:8) is defined with a prompt outside the choice
warning: default on the choice symbol SUPPORT_SLE_CENTRAL (defined at application/samples/products/sle_mouse_with_dongle/Kconfig:62, protocol/Kconfig:10) will have no effect, as defaults do not affect choice symbols
warning: the choice symbol SUPPORT_SLE_CENTRAL (defined at application/samples/products/sle_mouse_with_dongle/Kconfig:62, protocol/Kconfig:10) is defined with a prompt outside the choice
warning: default on the choice symbol SUPPORT_SLE_PERIPHERAL (defined at application/samples/products/sle_mouse_with_dongle/Kconfig:56, protocol/Kconfig:8) will have no effect, as defaults do not affect choice symbols
warning: the choice symbol SUPPORT_SLE_PERIPHERAL (defined at application/samples/products/sle_mouse_with_dongle/Kconfig:56, protocol/Kconfig:8) is defined with a prompt outside the choice
warning: default on the choice symbol SUPPORT_SLE_CENTRAL (defined at application/samples/products/sle_mouse_with_dongle/Kconfig:62, protocol/Kconfig:10) will have no effect, as defaults do not affect choice symbols
warning: the choice symbol SUPPORT_SLE_CENTRAL (defined at application/samples/products/sle_mouse_with_dongle/Kconfig:62, protocol/Kconfig:10) is defined with a prompt outside the choice
[Warning]:sdk libs import failed.
build reload D:\xfusion\sdks\bs2x_sdk\build\config\target_config\bs21e\menuconfig\acore\bs21e_sle_ble_slp_central_peripheral.config
Traceback (most recent call last):
D:\xfusion\sdks\bs2x_sdk\build\script\.\..\..\config.in
D:\xfusion\sdks\bs2x_sdk
File "D:\xfusion\sdks\bs2x_sdk\build.py", line 55, in <module>
No change to configuration in 'D:\xfusion\sdks\bs2x_sdk\build\script\.\..\..\build\config\target_config\bs21e\menuconfig\acore\bs21e_sle_ble_slp_central_peripheral.config'
builder.build()
D:\xfusion\sdks\bs2x_sdk\build\script\.\..\..\config.in
D:\xfusion\sdks\bs2x_sdk
File "D:\xfusion\sdks\bs2x_sdk\build\script\cmake_builder.py", line 106, in build
Kconfig header saved to 'D:\xfusion\sdks\bs2x_sdk\output\bs21e\acore\bs21e-sle-ble-slp-central-peripheral\mconfig.h'
self.build_target(target)
File "D:\xfusion\sdks\bs2x_sdk\build\script\cmake_builder.py", line 121, in build_target
self.compile_target(target, env)
File "D:\xfusion\sdks\bs2x_sdk\build\script\cmake_builder.py", line 242, in compile_target
self.start(env, target_name, output_path, clean=self.need_clean, nhso=self.no_hso)
File "D:\xfusion\sdks\bs2x_sdk\build\script\cmake_builder.py", line 376, in start
_excute(self.cmake_cmd, log_file, self.dump)
File "D:\xfusion\sdks\bs2x_sdk\build\script\cmake_builder.py", line 345, in _excute
errcode = exec_shell(cmd, log_file, is_dump)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\xfusion\sdks\bs2x_sdk\build\script\utils\build_utils.py", line 286, in exec_shell
subp = subprocess.Popen(cmd_list, shell=False)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1026, in __init__    
self._execute_child(args, executable, preexec_fn, close_fds,
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1538, in _execute_child
hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
(v1.2.0) PS D:\xfusion\hello> xf build
23:47:02: run build
23:47:02: scan config
23:47:02: scan config done
23:47:02: run script D:\xfusion\components\xf_hal\xf_collect.py
23:47:02: run script D:\xfusion\components\xf_heap\xf_collect.py
23:47:02: run script D:\xfusion\components\xf_init\xf_collect.py
23:47:02: run script D:\xfusion\components\xf_log\xf_collect.py
23:47:02: run script D:\xfusion\components\xf_nal\xf_collect.py
23:47:02: run script D:\xfusion\components\xf_net_apps\xf_collect.py
23:47:02: run script D:\xfusion\components\xf_osal\xf_collect.py
23:47:02: run script D:\xfusion\components\xf_sys\xf_collect.py
23:47:02: run script D:\xfusion\components\xf_task\xf_collect.py
23:47:02: run script D:\xfusion\components\xf_utils\xf_collect.py
23:47:02: run script D:\xfusion\components\xf_wal\xf_collect.py
23:47:02: run script D:\xfusion\hello\main\xf_collect.py
23:47:02: Template applied successfully to D:\xfusion\hello\build\build_environ.cmake
23:47:02: exec cmd python build.py -c -nhso -release bs21e-sle-ble-slp-central-peripheral
D:\xfusion\sdks\bs2x_sdk\build\script\sdk_generator\target_config_genarator.py:13: SyntaxWarning: invalid escape sequence '\s'
r = re.search("['\"]%s['\"](\s*):[\d\D\r\n]*?\}(\s*)," % config, lines)
D:\xfusion\sdks\bs2x_sdk\build\script\sdk_generator\target_config_genarator.py:16: SyntaxWarning: invalid escape sequence '\{'
lines = re.sub("(target|target_template) = \{\n([\w\W]*?\n)\}",
D:\xfusion\sdks\bs2x_sdk\build\script\sdk_generator\target_config_genarator.py:18: SyntaxWarning: invalid escape sequence '\{'
lines = re.sub("target_copy = \{\n([\w\W]*?\n)\}",
D:\xfusion\sdks\bs2x_sdk\build\script\sdk_generator\target_config_genarator.py:20: SyntaxWarning: invalid escape sequence '\{'
lines = re.sub("target_group = \{\n([\w\W]*?\n)\}",
warning: default on the choice symbol SUPPORT_SLE_PERIPHERAL (defined at application/samples/products/sle_mouse_with_dongle/Kconfig:56, protocol/Kconfig:8) will have no effect, as defaults do not affect choice symbols
warning: the choice symbol SUPPORT_SLE_PERIPHERAL (defined at application/samples/products/sle_mouse_with_dongle/Kconfig:56, protocol/Kconfig:8) is defined with a prompt outside the choice
warning: default on the choice symbol SUPPORT_SLE_CENTRAL (defined at application/samples/products/sle_mouse_with_dongle/Kconfig:62, protocol/Kconfig:10) will have no effect, as defaults do not affect choice symbols
warning: the choice symbol SUPPORT_SLE_CENTRAL (defined at application/samples/products/sle_mouse_with_dongle/Kconfig:62, protocol/Kconfig:10) is defined with a prompt outside the choice
warning: default on the choice symbol SUPPORT_SLE_PERIPHERAL (defined at application/samples/products/sle_mouse_with_dongle/Kconfig:56, protocol/Kconfig:8) will have no effect, as defaults do not affect choice symbols
warning: the choice symbol SUPPORT_SLE_PERIPHERAL (defined at application/samples/products/sle_mouse_with_dongle/Kconfig:56, protocol/Kconfig:8) is defined with a prompt outside the choice
warning: default on the choice symbol SUPPORT_SLE_CENTRAL (defined at application/samples/products/sle_mouse_with_dongle/Kconfig:62, protocol/Kconfig:10) will have no effect, as defaults do not affect choice symbols
warning: the choice symbol SUPPORT_SLE_CENTRAL (defined at application/samples/products/sle_mouse_with_dongle/Kconfig:62, protocol/Kconfig:10) is defined with a prompt outside the choice
[Warning]:sdk libs import failed.
Traceback (most recent call last):
build reload D:\xfusion\sdks\bs2x_sdk\build\config\target_config\bs21e\menuconfig\acore\bs21e_sle_ble_slp_central_peripheral.config
File "D:\xfusion\sdks\bs2x_sdk\build.py", line 55, in <module>
D:\xfusion\sdks\bs2x_sdk\build\script\.\..\..\config.in
builder.build()
File "D:\xfusion\sdks\bs2x_sdk\build\script\cmake_builder.py", line 106, in build
self.build_target(target)
File "D:\xfusion\sdks\bs2x_sdk\build\script\cmake_builder.py", line 121, in build_target
D:\xfusion\sdks\bs2x_sdk
No change to configuration in 'D:\xfusion\sdks\bs2x_sdk\build\script\.\..\..\build\config\target_config\bs21e\menuconfig\acore\bs21e_sle_ble_slp_central_peripheral.config'
D:\xfusion\sdks\bs2x_sdk\build\script\.\..\..\config.in
D:\xfusion\sdks\bs2x_sdk
Kconfig header saved to 'D:\xfusion\sdks\bs2x_sdk\output\bs21e\acore\bs21e-sle-ble-slp-central-peripheral\mconfig.h'
self.compile_target(target, env)
File "D:\xfusion\sdks\bs2x_sdk\build\script\cmake_builder.py", line 242, in compile_target
self.start(env, target_name, output_path, clean=self.need_clean, nhso=self.no_hso)
File "D:\xfusion\sdks\bs2x_sdk\build\script\cmake_builder.py", line 376, in start
_excute(self.cmake_cmd, log_file, self.dump)
File "D:\xfusion\sdks\bs2x_sdk\build\script\cmake_builder.py", line 345, in _excute
errcode = exec_shell(cmd, log_file, is_dump)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\xfusion\sdks\bs2x_sdk\build\script\utils\build_utils.py", line 286, in exec_shell
subp = subprocess.Popen(cmd_list, shell=False)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1026, in __init__    
self._execute_child(args, executable, preexec_fn, close_fds,
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1538, in _execute_child
hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
(v1.2.0) PS D:\xfusion\hello> python --version
Python 3.12.8
[Kconfig.zip](https://github.com/user-attachments/files/18266703/Kconfig.zip)

**Comment by geekheart** [comment]
你执行前有执行export嘛？每次新的命令行都需要

**Comment by bobo9795** [comment]
666
